name: cf_timing
channels:
  - ejolly
  - huggingface
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - aoo-mozilla-en-dict-au=2022.08.01
  - aoo-mozilla-en-dict-ca=2022.08.01
  - aoo-mozilla-en-dict-gb=2022.08.01
  - aoo-mozilla-en-dict-us=2022.08.01
  - aoo-mozilla-en-dict-za=2022.08.01
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35.1
  - blas=1.0
  - bleach=3.2.1
  - blosc=1.21.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.14.12
  - certifi=2022.9.24
  - cffi=1.14.6
  - click=8.0.1
  - curl=7.76.1
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=4.4.2
  - deepdish=0.3.7
  - defusedxml=0.6.0
  - enchant=2.3.1
  - entrypoints=0.3
  - expat=2.2.10
  - filelock=3.8.0
  - fontconfig=2.13.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - glib=2.68.4
  - glib-tools=2.68.4
  - graphite2=1.3.14
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=1.8.8
  - hdf5=1.10.4
  - huggingface_hub=0.10.1
  - hunspell=1.7.0
  - hunspell-en=2022.08.01
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2021.3.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libcurl=7.76.1
  - libedit=3.1.20210714
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.17
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - lzo=2.10
  - make=4.2.1
  - markupsafe=2.0.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.6.2
  - notebook=6.1.4
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1o
  - packaging=20.4
  - pandas=1.3.4
  - pandoc=2.11
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.8.0
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.2.2
  - pixman=0.40.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.15.8
  - ptyprocess=0.6.0
  - pycparser=2.21
  - pyenchant=3.2.2
  - pygments=2.7.1
  - pymer4=0.7.1
  - pyopenssl=22.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.10.2
  - pytz=2020.1
  - pyyaml=5.4.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - r-assertthat=0.2.1
  - r-base=3.6.1
  - r-bh=1.69.0_1
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-blob=1.1.1
  - r-boot=1.3_28
  - r-cli=1.1.0
  - r-colorspace=2.0_1
  - r-crayon=1.3.4
  - r-dbi=1.0.0
  - r-dbplyr=1.4.0
  - r-digest=0.6.27
  - r-dplyr=1.0.6
  - r-ellipsis=0.3.2
  - r-emmeans=1.3.4
  - r-estimability=1.3
  - r-fansi=0.4.0
  - r-generics=0.1.0
  - r-ggplot2=3.1.1
  - r-glue=1.4.2
  - r-gtable=0.3.0
  - r-labeling=0.4.2
  - r-lattice=0.20_44
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.0
  - r-lme4=1.1_21
  - r-lmertest=3.1_3
  - r-magrittr=1.5
  - r-mass=7.3_51.3
  - r-matrix=1.2_18
  - r-memoise=1.1.0
  - r-mgcv=1.8_31
  - r-minqa=1.2.4
  - r-munsell=0.5.0
  - r-mvtnorm=1.1_1
  - r-nlme=3.1_150
  - r-nloptr=1.2.2.2
  - r-numderiv=2016.8_1.1
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-prettyunits=1.0.2
  - r-purrr=0.3.4
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rcppeigen=0.3.3.7.0
  - r-reshape2=1.4.4
  - r-rlang=0.4.11
  - r-rsqlite=2.1.1
  - r-scales=1.0.0
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-tibble=2.1.3
  - r-tidyselect=1.1.1
  - r-utf8=1.2.1
  - r-vctrs=0.3.8
  - r-viridislite=0.4.0
  - r-withr=2.1.2
  - r-xtable=1.8_4
  - readline=8.1
  - regex=2021.8.3
  - rpy2=3.4.5
  - sacremoses=master
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.5.0
  - setuptools=58.0.4
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - statsmodels=0.13.0
  - sysroot_linux-64=2.17
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - tktable=2.10
  - tokenizers=0.10.3
  - tornado=6.1
  - tqdm=4.62.2
  - traitlets=5.0.5
  - transformers=4.14.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzlocal=2.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - alabaster==0.7.12
    - babel==2.9.1
    - black==21.12b0
    - build==0.7.0
    - charset-normalizer==2.0.9
    - colorama==0.4.4
    - coverage==6.2
    - cryptography==36.0.1
    - docutils==0.17.1
    - flake8==4.0.1
    - idna==3.3
    - imagesize==1.3.0
    - importlib-metadata==4.2.0
    - iniconfig==1.1.1
    - jeepney==0.7.1
    - keyring==23.4.0
    - m2r==0.2.1
    - mccabe==0.6.1
    - mypy-extensions==0.4.3
    - numpydoc==1.1.0
    - pathspec==0.9.0
    - pep517==0.12.0
    - pkginfo==1.8.2
    - platformdirs==2.4.1
    - pluggy==1.0.0
    - py==1.11.0
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - readme-renderer==32.0
    - requests==2.26.0
    - requests-toolbelt==0.9.1
    - rfc3986==1.5.0
    - secretstorage==3.3.1
    - snowballstemmer==2.2.0
    - sphinx==4.3.2
    - sphinx-rtd-theme==1.0.0
    - sphinx-sitemap==2.2.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sybil==3.0.0
    - tables==3.7.0
    - tabulate==0.8.9
    - toml==0.10.2
    - tomli==1.2.3
    - twine==3.7.1
    - typed-ast==1.5.1
    - urllib3==1.26.7
