name: cf
channels:
  - conda-forge
  - defaults
  - ejolly
dependencies:
  - python=3.8
  - pandas=1.5
  - tqdm
  - rpy2
  - hunspell-en
  - pyenchant
  - matplotlib
  - pymer4
  - seaborn
  - statsmodels
