name: cf_nn
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - aoo-mozilla-en-dict-au=2022.08.01
  - aoo-mozilla-en-dict-ca=2022.08.01
  - aoo-mozilla-en-dict-gb=2022.08.01
  - aoo-mozilla-en-dict-us=2022.08.01
  - aoo-mozilla-en-dict-za=2022.08.01
  - arrow-cpp=8.0.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - blinker=1.5
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - contourpy=1.0.6
  - cryptography=38.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.0.90
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cycler=0.11.0
  - dataclasses=0.8
  - datasets=2.8.0
  - dbus=1.13.18
  - dill=0.3.6
  - enchant=2.3.3
  - expat=2.5.0
  - fftw=3.3.9
  - filelock=3.6.0
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - gds-tools=1.5.0.59
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - glog=0.5.0
  - google-auth=2.15.0
  - google-auth-oauthlib=0.4.6
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - huggingface_hub=0.11.1
  - hunspell=1.7.0
  - hunspell-en=2022.08.01
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.2
  - lcms2=2.14
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcurl=7.86.0
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.14
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.74.1
  - libiconv=1.17
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - lightning-utilities=0.5.0
  - llvm-openmp=15.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - multiprocess=0.70.14
  - munkres=1.1.4
  - ncurses=6.3
  - nsight-compute=2022.4.0.15
  - nspr=4.35
  - nss=3.82
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - oauthlib=3.2.2
  - openssl=1.1.1s
  - orc=1.7.4
  - packaging=22.0
  - pandas=1.5.2
  - patsy=0.5.3
  - pcre2=10.40
  - pillow=9.3.0
  - pip=22.3.1
  - ply=3.11
  - protobuf=3.20.1
  - pyarrow=8.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyenchant=3.2.2
  - pyjwt=2.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-xxhash=2.0.2
  - python_abi=3.8
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-lightning=1.8.1
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - sacremoses=master
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.0
  - statsmodels=0.13.5
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.10.1
  - toml=0.10.2
  - torchmetrics=0.11.0
  - tornado=6.2
  - tqdm=4.64.1
  - transformers=4.6.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - unicodedata2=15.0.0
  - urllib3=1.26.13
  - utf8proc=2.6.1
  - werkzeug=2.1.2
  - wheel=0.37.1
  - xxhash=0.8.0
  - xz=5.2.8
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - evaluate==0.4.0
      - responses==0.18.0
