name: cf_nn
channels:
  - defaults
  - conda-forge
  - huggingface
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch
  - pytorch-cuda=11.6
  - transformers=4.6.1
  - datasets
  - pytorch-lightning
  - numpy=1.23
  - tokenizers=0.10.1
  - scipy
  - scikit-learn
  - hunspell-en
  - tqdm
  - seaborn
  - sentencepiece
  - matplotlib
  - pyenchant
  - pip
  - pip:
    - evaluate
