name: cf
channels:
  - conda-forge
  - defaults
  - ejolly/label/pre-release
dependencies:
  - python=3.8
  - pandas=1.5
  - tqdm
  - rpy2
  - hunspell-en
  - matplotlib
  - pymer4=0.8.0
  - seaborn
  - statsmodels
  - nltk
  - pip:
      - pyenchant
